config/routes.rb
Rails.application.routes.draw do
  resources :static_pages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "static_pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_static_page, only: %i[ show edit update destroy ]

  # GET /static_pages or /static_pages.json
  def index
    flickr = Flickr.new
    unless params[:user_id].blank?
      @photos = flickr.photos.search(user_id: params[:user_id])
    else
      @photos = flickr.photos.getRecent
    end
    @static_pages = StaticPage.all
  end

  # GET /static_pages/1 or /static_pages/1.json
  def show
  end

  # GET /static_pages/new
  def new
    @static_page = StaticPage.new
  end

  # GET /static_pages/1/edit
  def edit
  end

  # POST /static_pages or /static_pages.json
  def create
    @static_page = StaticPage.new(static_page_params)

    respond_to do |format|
      if @static_page.save
        format.html { redirect_to static_page_url(@static_page), notice: "Static page was successfully created." }
        format.json { render :show, status: :created, location: @static_page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /static_pages/1 or /static_pages/1.json
  def update
    respond_to do |format|
      if @static_page.update(static_page_params)
        format.html { redirect_to static_page_url(@static_page), notice: "Static page was successfully updated." }
        format.json { render :show, status: :ok, location: @static_page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_pages/1 or /static_pages/1.json
  def destroy
    @static_page.destroy

    respond_to do |format|
      format.html { redirect_to static_pages_url, notice: "Static page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static_page
      @static_page = StaticPage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def static_page_params
      params.fetch(:static_page, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlickrApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-dark">
      <a class="navbar-brand text-light" href="#">Flickr Search</a>
    </nav>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>

app/views/static_pages/_form.html.erb
<%= form_with(model: static_page) do |form| %>
  <% if static_page.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
        <% static_page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/static_pages/_search_form.html.erb
<div class="container mt-5 d-flex justify-content-center"> 
  <div class="row">
    <%= form_with(url: "/", method: 'get', local: true) do %>
      <div class="form-control mt-1 max-width: ">
        <%= text_field_tag :user_id, nil, placeholder: "Enter ID of User" %>
      </div>
      <div class="form-control mt-1">
        <%= submit_tag "Show Photos", class: "btn btn-block" %>
      </div>
  </div>
</div>
<% end %>

app/views/static_pages/_static_page.html.erb
<div id="<%= dom_id static_page %>">
</div>

app/views/static_pages/edit.html.erb
<h1>Editing static page</h1>

<%= render "form", static_page: @static_page %>

<br>

<div>
  <%= link_to "Show this static page", @static_page %> |
  <%= link_to "Back to static pages", static_pages_path %>
</div>

app/views/static_pages/index.html.erb
<% if params[:user_id].nil? %>
  <div class="container">
    <div class="row">
      <%= render 'search_form' %>
    <% else %>
      <%= render 'search_form' %>
    </div>
    <div class="container d-flex justify-content-center pt-5">
      <% @photos.each do |photo| %>
        <div class="col">
          <img src="<%=Flickr.url_n(photo) %>"/>
        </div>
      <% end %>
    </div>
  <% end %>

app/views/static_pages/new.html.erb
<h1>New static page</h1>

<%= render "form", static_page: @static_page %>

<br>

<div>
  <%= link_to "Back to static pages", static_pages_path %>
</div>

app/views/static_pages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @static_page %>

<div>
  <%= link_to "Edit this static page", edit_static_page_path(@static_page) %> |
  <%= link_to "Back to static pages", static_pages_path %>

  <%= button_to "Destroy this static page", @static_page, method: :delete %>
</div>